# Generated by Django 5.2.3 on 2025-06-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('LANCHES', 'Lanches'), ('BEBIDAS', 'Bebidas'), ('PORCOES', 'Porções'), ('SOBREMESAS', 'Sobremesas'), ('ADICIONAIS', 'Adicionais')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
    ]
