# Generated by Django 5.2.3 on 2025-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='produtos/default.jpg', null=True, upload_to='produtos/'),
        ),
    ]
